version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    commit-message:
      prefix: '[SKIP CI] '
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    commit-message:
      prefix: '[BUILD] '
    open-pull-requests-limit: 10
